### ISSUE TITLE
Can't use underscore-db 0.9.1 with lowdb 0.12.5 - TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rribou** [typicode/underscore-db#8]
I was using lowdb and underscore-db without problem until now. But method where() doesn't exist anymore in newer versions of lodash, so each time I want to use a method from underscore-db, I get the following message : TypeError: undefined is not a function. 
All was working fine with underscore-db 0.8.1 and lowdb 0.8.1.

Here is my previous code :
`var low = require('lowdb');  
low.mixin(require('underscore-db'));  
var db = low('db.json');  
var users = db('users).removeWhere({id: 1});`

I am now using :
`var low = require('lowdb');  
var db = low('db.json');  
db._.mixin(require('underscore-db'));  
var users = db('users).removeWhere({id: 1});`

**Comment by typicode** [comment]
Thanks for the heads up :+1: 
I'll check that.

**Comment by rribou** [comment]
As a workaround I'm using `wr.db._.mixin({
    where: function () {
        return this.filter.apply(arguments);
    }
});`

**Comment by typicode** [comment]
Just released `v0.10.0` it should be good.
